#!/usr/bin/env python3
import argparse
import pathlib


def main() -> int:
    parser = argparse.ArgumentParser(description="Turn a spec into scaffolded project files")
    parser.add_argument("--name", required=True)
    parser.add_argument("--output", default=".")
    parser.add_argument("--spec", required=True)
    ns = parser.parse_args()

    root = pathlib.Path(ns.output) / ns.name
    src = root / "src"
    tests = root / "tests"
    docs = root / "docs"
    src.mkdir(parents=True, exist_ok=True)
    tests.mkdir(parents=True, exist_ok=True)
    docs.mkdir(parents=True, exist_ok=True)

    (docs / "SPEC.md").write_text(pathlib.Path(ns.spec).read_text())
    (src / "main.py").write_text("def main():\n    print(\"hello from scaffold\")\n\n\nif __name__ == '__main__':\n    main()\n")
    (tests / "test_smoke.py").write_text("def test_smoke():\n    assert True\n")
    (root / "README.md").write_text(f"# {ns.name}\n\nGenerated by spec2scaffold.\n")

    print(str(root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
